//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 02:02:24 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.fiusb.ci.infosys.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.infosys.ci.fiusb.webservice;
