//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.11 at 11:05:51 AM WAT 
//


package com.infosys.ci.fiusb.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageKey" type="{http://webservice.fiusb.ci.infosys.com}MessageKey"/>
 *         &lt;element name="RequestMessageInfo" type="{http://webservice.fiusb.ci.infosys.com}RequestMessageInfo"/>
 *         &lt;element name="Security" type="{http://webservice.fiusb.ci.infosys.com}Security"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestHeader", propOrder = {
    "messageKey",
    "requestMessageInfo",
    "security"
})
public class RequestHeader {

    @XmlElement(name = "MessageKey", required = true)
    protected MessageKey messageKey;
    @XmlElement(name = "RequestMessageInfo", required = true)
    protected RequestMessageInfo requestMessageInfo;
    @XmlElement(name = "Security", required = true)
    protected Security security;

    /**
     * Gets the value of the messageKey property.
     * 
     * @return
     *     possible object is
     *     {@link MessageKey }
     *     
     */
    public MessageKey getMessageKey() {
        return messageKey;
    }

    /**
     * Sets the value of the messageKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageKey }
     *     
     */
    public void setMessageKey(MessageKey value) {
        this.messageKey = value;
    }

    /**
     * Gets the value of the requestMessageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RequestMessageInfo }
     *     
     */
    public RequestMessageInfo getRequestMessageInfo() {
        return requestMessageInfo;
    }

    /**
     * Sets the value of the requestMessageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestMessageInfo }
     *     
     */
    public void setRequestMessageInfo(RequestMessageInfo value) {
        this.requestMessageInfo = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }
    
    @Override
    public String toString () {
        return "RequestHeader{" +
              "messageKey=" + messageKey +
              ", requestMessageInfo=" + requestMessageInfo +
              ", security=" + security +
              '}';
    }
}
