//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 10:37:15 AM GMT+01:00 
//


package com.old.customAcctDetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for executeFinacleScript_CustomData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="executeFinacleScript_CustomData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="solId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="crncyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="freezeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcctBal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schmType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schmCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schmCodeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctOfficerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctOfficerCodeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctBrokerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brokerCodeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctSMSStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctEmailStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SuccessOrFailure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeFinacleScript_CustomData", propOrder = {
    "solId",
    "crncyCode",
    "acctName",
    "freezeCode",
    "acctBal",
    "schmType",
    "schmCode",
    "schmCodeDesc",
    "acctOfficerCode",
    "acctOfficerCodeDesc",
    "acctBrokerCode",
    "brokerCodeDesc",
    "acctStatus",
    "acctSMSStatus",
    "acctEmailStatus",
    "successOrFailure"
})
public class ExecuteFinacleScriptCustomData {

    @XmlElement(required = true)
    protected String solId = "001";
    @XmlElement(required = true)
    protected String crncyCode = "NGN";
    @XmlElement(required = true)
    protected String acctName = "OKOROAFOR VINCENT ONYEKWERE";
    @XmlElement(required = true)
    protected String freezeCode = "null";
    @XmlElement(name = "AcctBal", required = true)
    protected String acctBal = "375.66";
    @XmlElement(required = true)
    protected String schmType = "CAA";
    @XmlElement(required = true)
    protected String schmCode = "CA202";
    @XmlElement(required = true)
    protected String schmCodeDesc = "PREMIUM CURRENT";
    @XmlElement(required = true)
    protected String acctOfficerCode = "001DE";
    @XmlElement(required = true)
    protected String acctOfficerCodeDesc = "UGOH JACINTA CHINONSO";
    @XmlElement(required = true)
    protected String acctBrokerCode = "D1782";
    @XmlElement(required = true)
    protected String brokerCodeDesc = "ENEJE JANE ONYINYE";
    @XmlElement(required = true)
    protected String acctStatus = "I";
    @XmlElement(required = true)
    protected String acctSMSStatus = "N";
    @XmlElement(required = true)
    protected String acctEmailStatus = "NULL";
    @XmlElement(name = "SuccessOrFailure", required = true)
    protected String successOrFailure = "SUCCESS";

    /**
     * Gets the value of the solId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolId() {
        return solId;
    }

    /**
     * Sets the value of the solId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolId(String value) {
        this.solId = value;
    }

    /**
     * Gets the value of the crncyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrncyCode() {
        return crncyCode;
    }

    /**
     * Sets the value of the crncyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrncyCode(String value) {
        this.crncyCode = value;
    }

    /**
     * Gets the value of the acctName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctName() {
        return acctName;
    }

    /**
     * Sets the value of the acctName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctName(String value) {
        this.acctName = value;
    }

    /**
     * Gets the value of the freezeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreezeCode() {
        return freezeCode;
    }

    /**
     * Sets the value of the freezeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreezeCode(String value) {
        this.freezeCode = value;
    }

    /**
     * Gets the value of the acctBal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctBal() {
        return acctBal;
    }

    /**
     * Sets the value of the acctBal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctBal(String value) {
        this.acctBal = value;
    }

    /**
     * Gets the value of the schmType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchmType() {
        return schmType;
    }

    /**
     * Sets the value of the schmType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchmType(String value) {
        this.schmType = value;
    }

    /**
     * Gets the value of the schmCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchmCode() {
        return schmCode;
    }

    /**
     * Sets the value of the schmCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchmCode(String value) {
        this.schmCode = value;
    }

    /**
     * Gets the value of the schmCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchmCodeDesc() {
        return schmCodeDesc;
    }

    /**
     * Sets the value of the schmCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchmCodeDesc(String value) {
        this.schmCodeDesc = value;
    }

    /**
     * Gets the value of the acctOfficerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctOfficerCode() {
        return acctOfficerCode;
    }

    /**
     * Sets the value of the acctOfficerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctOfficerCode(String value) {
        this.acctOfficerCode = value;
    }

    /**
     * Gets the value of the acctOfficerCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctOfficerCodeDesc() {
        return acctOfficerCodeDesc;
    }

    /**
     * Sets the value of the acctOfficerCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctOfficerCodeDesc(String value) {
        this.acctOfficerCodeDesc = value;
    }

    /**
     * Gets the value of the acctBrokerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctBrokerCode() {
        return acctBrokerCode;
    }

    /**
     * Sets the value of the acctBrokerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctBrokerCode(String value) {
        this.acctBrokerCode = value;
    }

    /**
     * Gets the value of the brokerCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerCodeDesc() {
        return brokerCodeDesc;
    }

    /**
     * Sets the value of the brokerCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerCodeDesc(String value) {
        this.brokerCodeDesc = value;
    }

    /**
     * Gets the value of the acctStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctStatus() {
        return acctStatus;
    }

    /**
     * Sets the value of the acctStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctStatus(String value) {
        this.acctStatus = value;
    }

    /**
     * Gets the value of the acctSMSStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctSMSStatus() {
        return acctSMSStatus;
    }

    /**
     * Sets the value of the acctSMSStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctSMSStatus(String value) {
        this.acctSMSStatus = value;
    }

    /**
     * Gets the value of the acctEmailStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctEmailStatus() {
        return acctEmailStatus;
    }

    /**
     * Sets the value of the acctEmailStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctEmailStatus(String value) {
        this.acctEmailStatus = value;
    }

    /**
     * Gets the value of the successOrFailure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccessOrFailure() {
        return successOrFailure;
    }

    /**
     * Sets the value of the successOrFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccessOrFailure(String value) {
        this.successOrFailure = value;
    }

}
