//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 10:37:15 AM GMT+01:00 
//


package com.old.customAcctDetails;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.DatatypeConfigurationException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infosys.ci.fiusb.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infosys.ci.fiusb.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExecuteServiceResponse }
     * 
     */
    public ExecuteServiceResponse createExecuteServiceResponse() {
        return new ExecuteServiceResponse();
    }

    /**
     * Create an instance of {@link FIXML }
     * 
     */
    public FIXML createFIXML() throws DatatypeConfigurationException {
        return new FIXML();
    }

    /**
     * Create an instance of {@link ExecuteService }
     * 
     */
    public ExecuteService createExecuteService() throws DatatypeConfigurationException {
        return new ExecuteService();
    }

    /**
     * Create an instance of {@link Arg00 }
     * 
     */
    public Arg00 createArg00() throws DatatypeConfigurationException {
        return new Arg00();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() throws DatatypeConfigurationException {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ResponseMessageInfo }
     * 
     */
    public ResponseMessageInfo createResponseMessageInfo() throws DatatypeConfigurationException {
        return new ResponseMessageInfo();
    }

    /**
     * Create an instance of {@link ExecuteFinacleScriptOutputVO }
     * 
     */
    public ExecuteFinacleScriptOutputVO createExecuteFinacleScriptOutputVO() {
        return new ExecuteFinacleScriptOutputVO();
    }

    /**
     * Create an instance of {@link MessageKey }
     * 
     */
    public MessageKey createMessageKey() {
        return new MessageKey();
    }

    /**
     * Create an instance of {@link HostTransaction }
     * 
     */
    public HostTransaction createHostTransaction() {
        return new HostTransaction();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() throws DatatypeConfigurationException {
        return new Header();
    }

    /**
     * Create an instance of {@link HostParentTransaction }
     * 
     */
    public HostParentTransaction createHostParentTransaction() {
        return new HostParentTransaction();
    }

    /**
     * Create an instance of {@link ExecuteFinacleScriptCustomData }
     * 
     */
    public ExecuteFinacleScriptCustomData createExecuteFinacleScriptCustomData() {
        return new ExecuteFinacleScriptCustomData();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() throws DatatypeConfigurationException {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link RequestMessageInfo }
     * 
     */
    public RequestMessageInfo createRequestMessageInfo() throws DatatypeConfigurationException {
        return new RequestMessageInfo();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link ExecuteFinacleScriptResponse }
     * 
     */
    public ExecuteFinacleScriptResponse createExecuteFinacleScriptResponse() {
        return new ExecuteFinacleScriptResponse();
    }

    /**
     * Create an instance of {@link UBUSTransaction }
     * 
     */
    public UBUSTransaction createUBUSTransaction() {
        return new UBUSTransaction();
    }

}
