//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 10:37:15 AM GMT+01:00 
//


package com.old.customAcctDetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;


/**
 * <p>Java class for RequestHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageKey" type="{http://webservice.fiusb.ci.infosys.com}MessageKey"/>
 *         &lt;element name="RequestMessageInfo" type="{http://webservice.fiusb.ci.infosys.com}RequestMessageInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestHeader", propOrder = {
    "messageKey",
    "requestMessageInfo"
})
public class RequestHeader {

    @XmlElement(name = "ResponseMessageInfo", required = true)
    protected RequestMessageInfo requestMessageInfo = new RequestMessageInfo();
    @XmlElement(name = "MessageKey", required = true)
    protected RequestMessageKey messageKey = new RequestMessageKey();

    public RequestHeader() throws DatatypeConfigurationException {
    }

    /**
     * Gets the value of the messageKey property.
     * 
     * @return
     *     possible object is
     *     {@link MessageKey }
     *     
     */
    public RequestMessageKey getMessageKey() {
        return messageKey;
    }

    /**
     * Sets the value of the messageKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageKey }
     *     
     */
    public void setMessageKey(RequestMessageKey value) {
        this.messageKey = value;
    }

    /**
     * Gets the value of the requestMessageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMessageInfo }
     *     
     */
    public RequestMessageInfo getRequestMessageInfo() {
        return requestMessageInfo;
    }

    /**
     * Sets the value of the requestMessageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMessageInfo }
     *     
     */
    public void setResponseMessageInfo(RequestMessageInfo value) {
        this.requestMessageInfo = value;
    }

}
