//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.01 at 02:28:42 PM GMT+01:00 
//


package com.soapws.webservice.customerUpdate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RetCustModResponse" type="{http://webservice.fiusb.ci.infosys.com}RetCustModResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "retCustModResponse"
})
public class Body {

    @XmlElement(name = "RetCustModResponse", required = true)
    protected RetCustModResponse retCustModResponse;

    /**
     * Gets the value of the retCustModResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RetCustModResponse }
     *     
     */
    public RetCustModResponse getRetCustModResponse() {
        return retCustModResponse;
    }

    /**
     * Sets the value of the retCustModResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetCustModResponse }
     *     
     */
    public void setRetCustModResponse(RetCustModResponse value) {
        this.retCustModResponse = value;
    }

}
