//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.01 at 02:23:50 PM GMT+01:00 
//


package com.soapws.executeFInScript;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="executeServiceReturn" type="{http://webservice.fiusb.ci.infosys.com}executeServiceReturn"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "executeServiceReturn"
})
@XmlRootElement(name = "executeServiceResponse")
public class ExecuteServiceResponse {

    @XmlElement(required = true)
    protected ExecuteServiceReturn executeServiceReturn;

    public ExecuteServiceResponse() {
    }

    /**
     * Gets the value of the executeServiceReturn property.
     * 
     * @return
     *     possible object is
     *     {@link ExecuteServiceReturn }
     *     
     */
    public ExecuteServiceReturn getExecuteServiceReturn() {
        return executeServiceReturn;
    }

    /**
     * Sets the value of the executeServiceReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecuteServiceReturn }
     *     
     */
    public void setExecuteServiceReturn(ExecuteServiceReturn value) {
        this.executeServiceReturn = value;
    }

}
