//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 05:12:58 PM GMT+01:00 
//


package com.soapws.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SignatureAddResponse" type="{http://webservice.fiusb.ci.infosys.com}SignatureAddResponse"/>
 *         &lt;element name="RetCustModResponse" type="{http://webservice.fiusb.ci.infosys.com}RetCustModResponse"/>
 *         &lt;element name="executeFinacleScriptResponse" type="{http://webservice.fiusb.ci.infosys.com}executeFinacleScriptResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "signatureAddResponse",
    "retCustModResponse",
    "executeFinacleScriptResponse"
})
public class Body {

    @XmlElement(name = "SignatureAddResponse", required = true)
    protected SignatureAddResponse signatureAddResponse = new SignatureAddResponse();
    @XmlElement(name = "RetCustModResponse", required = true)
    protected RetCustModResponse retCustModResponse = new RetCustModResponse();
    @XmlElement(required = true)
    protected ExecuteFinacleScriptResponse executeFinacleScriptResponse = new ExecuteFinacleScriptResponse();

    /**
     * Gets the value of the signatureAddResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureAddResponse }
     *     
     */
    public SignatureAddResponse getSignatureAddResponse() {
        return signatureAddResponse;
    }

    /**
     * Sets the value of the signatureAddResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureAddResponse }
     *     
     */
    public void setSignatureAddResponse(SignatureAddResponse value) {
        this.signatureAddResponse = value;
    }

    /**
     * Gets the value of the retCustModResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RetCustModResponse }
     *     
     */
    public RetCustModResponse getRetCustModResponse() {
        return retCustModResponse;
    }

    /**
     * Sets the value of the retCustModResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetCustModResponse }
     *     
     */
    public void setRetCustModResponse(RetCustModResponse value) {
        this.retCustModResponse = value;
    }

    /**
     * Gets the value of the executeFinacleScriptResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ExecuteFinacleScriptResponse }
     *     
     */
    public ExecuteFinacleScriptResponse getExecuteFinacleScriptResponse() {
        return executeFinacleScriptResponse;
    }

    /**
     * Sets the value of the executeFinacleScriptResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecuteFinacleScriptResponse }
     *     
     */
    public void setExecuteFinacleScriptResponse(ExecuteFinacleScriptResponse value) {
        this.executeFinacleScriptResponse = value;
    }

}
