//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 12:39:42 PM WAT 
//


package com.soapws.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for executeFinacleScriptResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="executeFinacleScriptResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExecuteFinacleScriptOutputVO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="executeFinacleScript_CustomData" type="{http://webservice.fiusb.ci.infosys.com}executeFinacleScript_CustomData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeFinacleScriptResponse", propOrder = {
    "executeFinacleScriptOutputVO",
    "executeFinacleScriptCustomData"
})
public class ExecuteFinacleScriptResponse {

    @XmlElement(name = "ExecuteFinacleScriptOutputVO", required = true)
    protected String executeFinacleScriptOutputVO = " ";
    @XmlElement(name = "executeFinacleScript_CustomData", required = true)
    protected ExecuteFinacleScriptCustomData executeFinacleScriptCustomData = new ExecuteFinacleScriptCustomData();

    /**
     * Gets the value of the executeFinacleScriptOutputVO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecuteFinacleScriptOutputVO() {
        return executeFinacleScriptOutputVO;
    }

    /**
     * Sets the value of the executeFinacleScriptOutputVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecuteFinacleScriptOutputVO(String value) {
        this.executeFinacleScriptOutputVO = value;
    }

    /**
     * Gets the value of the executeFinacleScriptCustomData property.
     * 
     * @return
     *     possible object is
     *     {@link ExecuteFinacleScriptCustomData }
     *     
     */
    public ExecuteFinacleScriptCustomData getExecuteFinacleScriptCustomData() {
        return executeFinacleScriptCustomData;
    }

    /**
     * Sets the value of the executeFinacleScriptCustomData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecuteFinacleScriptCustomData }
     *     
     */
    public void setExecuteFinacleScriptCustomData(ExecuteFinacleScriptCustomData value) {
        this.executeFinacleScriptCustomData = value;
    }

}
